language: php

php:
    - '7.1'
    - '7.2'
    - '7.3'
    - nightly

install:
    - composer install
    - composer require --dev phpstan/phpstan-shim szepeviktor/phpstan-wordpress

script:
    - ./vendor/bin/phpunit --testdox --coverage-clover=coverage/report/coverage.xml
    - ./vendor/bin/phpstan analyze
    - ./vendor/bin/phpcs

after_success:
    - bash <(curl -s https://codecov.io/bash)
